import { useState } from 'react';

// Import the contract factory from the folder generated by the fuelchain
// command
import { useReward } from 'react-rewards';
import CardHeading from './CardHeading';
import LoginForm from './LoginForm';
import WalletView from './WalletView';

function App() {
    const { reward } = useReward('confettiId', 'confetti', {
        lifetime: 300,
        colors: ['#57bf9d', '#ffffff', '#09081a'], // fuel colors
    });
    const downloadTxtFile = () => {
        const element = document.createElement('a');
        const file = new Blob(
            ['0x976e5c3fa620092c718d852ca703b6da9e3075b9f2ecb8ed42d9f746bf26aafb'],
            { type: 'text/plain' },
        );
        element.href = URL.createObjectURL(file);
        element.download = 'Backup Key - DO NOT SHARE.txt';
        document.body.appendChild(element); // Required for this to work in FireFox
        element.click();
    };

    const [showSend, setShowSend] = useState(false);
    const [txSent, setTxSent] = useState(false);

    const onSubmit = (data: any) => {
        console.log('on submit', data);
        downloadTxtFile(); // download the backup file
        setShowSend(true);
    };

    const onFinale = async (data: any) => {
        console.log('on finale', data);
        const runTx = await fetch('http://localhost:5005/sendtx', {
            method: 'GET', // default, so we can ignore
        });
        console.log('Finished running tx', runTx);

        reward(); // confetti
    };
    
    return (
        <div className="h-screen bg-green-100 w-100">
            {/* <img
                alt=""
                src="./logo.webp"
                style={{
                    maxWidth: 100,
                    textAlign: 'center',
                    margin: '0 auto',
                    borderRadius: '50%',
                }}
            /> */}
            {showSend ? (
                <div className="flex flex-col justify-center min-h-full py-12 sm:px-6 lg:px-8">
                    <CardHeading heading="Wallet" subHeading="Transfer your assets." />
                    {txSent ?(
                      <div></div>
                    ) : <WalletView onSubmit={onFinale} />}
                </div>
            ) : (
                <div className="flex flex-col justify-center min-h-full py-12 sm:px-6 lg:px-8">
                    <CardHeading
                        heading="Authsome"
                        subHeading="Create your multi-sig wallet."
                    />
                    <LoginForm onSubmit={onSubmit} />
                </div>
            )}
        </div>
    );
}

export default App;
