import { useState } from "react";

// Import the contract factory from the folder generated by the fuelchain
// command
import { useReward } from "react-rewards";

function App() {
  const { reward } = useReward("confettiId", "confetti", {
    lifetime: 300,
    colors: ["#57bf9d", "#ffffff", "#09081a"], // fuel colors
  });
  const downloadTxtFile = () => {
    const element = document.createElement("a");
    const file = new Blob(
      ["0x976e5c3fa620092c718d852ca703b6da9e3075b9f2ecb8ed42d9f746bf26aafb"],
      { type: "text/plain" }
    );
    element.href = URL.createObjectURL(file);
    element.download = "Backup Key - DO NOT SHARE.txt";
    document.body.appendChild(element); // Required for this to work in FireFox
    element.click();
  };

  const [showSend, setShowSend] = useState(false);

  const onSubmit = (data: any) => {
    downloadTxtFile(); // download the backup file
    setShowSend(true);
  };
  const onFinale = async (data: any) => {
    const runTx = await fetch("http://localhost:5005/sendtx", {
      method: "GET", // default, so we can ignore
    });
    console.log("Finsihed running tx", runTx);

    reward(); // confetti
  };
  return (
    <div className="h-screen w-100 bg-gray-800">
      <div className="bg-gray-300 text-gray-600 w-6/12 px-20 py-12 relative top-2/4 left-2/4 translate-y-[-50%] translate-x-[-50%] rounded-lg text-center">
        <img
          src="./logo.jpg"
          style={{
            maxWidth: 100,
            textAlign: "center",
            margin: "0 auto",
            borderRadius: "50%",
          }}
        />
        <h2 className="text-4xl font-bold mb-4">Authsome</h2>
        {showSend ? (
          <>
            <label
              className="mb-1 block text-lg text-gray-600 font-semibold"
              htmlFor="amount"
            >
              Amount
            </label>
            <input
              className="block w-full px-4 py-2 rounded-sm bg-gray-400 text-white placeholder-gray-200 border-2 border-[#6b728049] focus:outline focus:outline-1 focus:outline-blue-500"
              type="text"
              placeholder="Amount"
            />
            <br />
            <label
              className="mb-1 block text-lg text-gray-600 font-semibold"
              htmlFor="amount"
            >
              Recipient
            </label>
            <input
              className="block w-full px-4 py-2 rounded-sm bg-gray-400 text-white placeholder-gray-200 border-2 border-[#6b728049] focus:outline focus:outline-1 focus:outline-blue-500"
              type="text"
              placeholder="Recipient"
            />
            <br />
            <div style={{ textAlign: "center" }}>
              <button
                id="confettiId"
                style={{ margin: "0 auto", textAlign: "center" }}
                className="px-4 py-2 mt-2 bg-green-700 text-white text-sm font-semibold rounded-md uppercase hover:opacity-70 transition-opacity transition-duration-300"
                onClick={onFinale}
              >
                Send TX
              </button>
            </div>
          </>
        ) : (
          <form className="text-left">
            <label
              className="mb-1 block text-lg text-gray-600 font-semibold"
              htmlFor="email"
            >
              Email
            </label>
            <input
              className="block w-full px-4 py-2 rounded-sm bg-gray-400 text-white placeholder-gray-200 border-2 border-[#6b728049] focus:outline focus:outline-1 focus:outline-blue-500"
              type="text"
              placeholder="Email"
            />
            <br />
            <div style={{ textAlign: "center" }}>
              <button
                style={{ margin: "0 auto", textAlign: "center" }}
                className="px-4 py-2 mt-2 bg-green-700 text-white text-sm font-semibold rounded-md uppercase hover:opacity-70 transition-opacity transition-duration-300"
                type="submit"
                onClick={onSubmit}
              >
                Login with Fuel ⚡
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}

export default App;
